# config/transforms.yaml

# Список трансформаций, которые будут подгружены в CoordinateTransformer
transforms:
  - parent_frame: world
    child_frame: robot_base
    translation: [0.0, 0.0, 0.0]
    rotation:    [0.0, 0.0, 0.0, 1.0]
  - parent_frame: robot_base
    child_frame: tool0
    translation: [0.1, 0.0, 0.2]
    rotation:    [0.0, 0.0, 0.7071, 0.7071]

# Границы (min/max) для систем отсчёта
bounds:
  world:
    min: [-2.0, -2.0, -1.0]
    max: [ 2.0,  2.0,  2.0]
  robot_base:
    min: [-1.0, -1.0,  0.0]
    max: [ 1.0,  1.0,  1.5]
  tool0:
    min: [-0.5, -0.5, -0.1]
    max: [ 0.5,  0.5,  0.5]

